### ISSUE TITLE
Colored Glass particles go out of bounds (with certain high settings)

### ISSUE THREAD

**Issue by SteveRussell33** [alexey-komarov/fruitsofkarma-vcvrack#2]
![image](https://user-images.githubusercontent.com/41975381/166623253-0387b91f-c03f-4e6b-a12e-0c726652bc50.png)

**Comment by alexey-komarov** [comment]
@SteveRussell33 Thanks, will look into it. Could you please attach and export your preset in json?

**Comment by SteveRussell33** [comment]
[ColoredGlass.zip](https://github.com/alexey-komarov/fruitsofkarma-vcvrack/files/8619797/ColoredGlass.zip)

**Comment by alexey-komarov** [comment]
Fixed with nvgScissors
