### ISSUE TITLE
Colored Glass CPU hog on Reset

### ISSUE THREAD

**Issue by vcvrackideas** [alexey-komarov/fruitsofkarma-vcvrack#6]
Приветствую Алексей, большое спасибо за модули, отдельно за Colored Glass,  теперь это лучший визуализатор в VCV! 
Заметил что при нажатии по Reset процессор подпрыгивает до 11%, и если нажать несколько раз подряд то и 18 бывает. Было бы здорово если можно исправить, пригодилось бы для визуализации отдельных триггеров например.
P.S попробовал подключить клок от Impromptu вообще весь Рэк визуально повис, процессор показал 100%

**Comment by alexey-komarov** [comment]
Здравствуйте, спасибо за фидбек, да, можно, займусь в ближайшее свободное время, но будет работать немного иначе. Суть в том, что сейчас при инициализации particles сразу рассчитывается randomness value и каждый Rand knob по сути является аттенюатором для заранее расчитанных randomных значений. Я могу сделать копию уже проинициалированного массива частиц, таким образом reset будет просто восстанавливать исходные значения, а не расситывать все заново.

**Comment by alexey-komarov** [comment]
Я запушил патч в rc ветку: https://github.com/alexey-komarov/fruitsofkarma-vcvrack/commit/62c4f59ddaf66957b898eaa7b3f337bb72197b88

**Comment by vcvrackideas** [comment]
Спасибо Алексей, работает отлично. Особенность прикольная - на широкий гейт реагирует как дерганно, пока он включен, а на узкий (триггер) как и предполагается, просто делает reset. Я думаю что это интересная конфигурация. 
А как-то можно, возможно в дальнейшем, расширить окно визуализации например в сторону чтобы черного фона было побольше? Например при большом зумировании вполне можно записывать графику в видеофайл. Я видел похожее как-то в одном модуле, но уже не помню в каком именно.

**Comment by alexey-komarov** [comment]
Там много что можно доработать, у меня есть тоже несколько идей, но пока не хвататет свободного времени.
Не совсем понял про черный фон, к сожалению размер модуля рэка жестко ограничен по высоте, а так бы я его конечно сделал бы высотой в два модуля
